= NMEA2000_mcp library for Arduino =

Inherited object for use NMEA2000 library for Arduino Boards with
MCP2515 CAN bus controller. See also NMEA2000 library.

To use this library, you will also need NMEA2000 library and
developed version of mcp_can library, which you can download from
https://github.com/ttlappalainen/CAN_BUS_Shield until changes has been implemented
to original https://github.com/Seeed-Studio/CAN_BUS_Shield library.

== Changes ==
27.03.2020 Added ICACHE_RAM_ATTR to Can1Interrupt by TyphoonSB.

18.07.2019 !Critical fix for interrupt receive. If receive buffer got full, interrupt started to loop and system hanged.
After fix if buffer gets full, incoming frames will be ignored, but system does not hang.

04.10.2018 Get rid of min(...) for better compatibility.

12.09.2017 Improved ISR speed 50% by improving mcp_can.

08.09.2017 Fix for sending. Both receiving and sending will be handled by interrupt. Requires improved mcp_can.

02.02.2016 Fix for sending. Interrupt has to be disabled during send, if interrupt is in use.

23.01.2016 Interrupt support for receiving.

== License ==

2015-2019 Copyright (c) Kave Oy, www.kave.fi  All right reserved.

Author: Timo Lappalainen

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
